// Release-readiness check 1: for every claim cited by a public artifact, re-open its source and record the result.
// Re-runs what can be re-run (commands, greps, fetches, the validator); claims that rest on a recorded run are checked against that record.
//   bun actualize/evidence/release-readiness/ledger-walk.mjs      -> ledger-walk.md and ledger-walk.json next to this file
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { parseModel, parseStamp, validateArtifact, staleReasons, GRADES, PUBLIC_GRADES } from "../../../hooks/src/lib/md.mjs";
import { loadLenses, waves } from "../../../hooks/src/lib/lenses.mjs";
import { BLOCK_TYPES } from "../../../cockpit/protocol/spec.ts";
import { REQUEST_STATUSES } from "../../../cockpit/protocol/work.ts";
const root = path.resolve(import.meta.dir, "../../..");
process.chdir(root);
const R = (...p) => path.join(root, ...p), read = (p) => fs.readFileSync(R(p), "utf8");
const sh = (c) => { const r = Bun.spawnSync(["bash", "-c", c], { stdout: "pipe", stderr: "pipe", cwd: root }); return { code: r.exitCode, out: new TextDecoder().decode(r.stdout) + new TextDecoder().decode(r.stderr) }; };
const model = parseModel(read("actualize/product-model.md"));
const publicArts = fs.readdirSync(R("actualize/artifacts"), { recursive: true }).filter((f) => f.endsWith(".md") && !f.includes("release-readiness")).map((f) => ({ f, text: read("actualize/artifacts/" + f) })).filter((a) => parseStamp(a.text).public);
const cited = new Map(); for (const a of publicArts) for (const c of parseStamp(a.text).cites) (cited.get(c) ?? cited.set(c, []).get(c)).push(a.f);
const norm = (s) => s.replace(/[\u2018\u2019]/g, "'").replace(/\s+/g, " ").toLowerCase();
const web = async (u, phrases) => { try { const r = await fetch(u, { redirect: "follow", headers: { "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) release-readiness" } }); const t = norm(await r.text()); if (r.status !== 200) return [false, `HTTP ${r.status}`]; const miss = phrases.filter((p) => !t.includes(norm(p))); return [miss.length === 0, miss.length ? `missing: ${miss.join(" | ")}` : `HTTP 200, found ${phrases.length} phrase(s)`]; } catch (e) { return [false, "blocked: " + e.message.slice(0, 60)]; } };
const qa = JSON.parse(read("actualize/evidence/fidelity-qa/site-qa.json")).results; const qaOk = (...ids) => ids.every((id) => qa.filter((r) => r.id === id).length > 0 && qa.filter((r) => r.id === id).every((r) => r.pass));
const loam = parseModel(fs.readFileSync(R("tests/walkthrough/product-model.md"), "utf8"));
const lensMap = loadLenses();
const checks = {
  C1: () => { const n = fs.readdirSync(R("skills")).filter((d) => fs.existsSync(R("skills", d, "SKILL.md"))).length; const l = sh("bun hooks/src/cli.mjs lenses").out.split("\n").filter((x) => /^[a-z]/.test(x)).length; return [n === 19 && l === 17, `${n} skill directories, ${l} lenses listed`]; },
  C2: () => [GRADES.size === 7 && PUBLIC_GRADES.size === 2, `${GRADES.size} grades, ${PUBLIC_GRADES.size} public`],
  C3: () => { const art = fs.readFileSync(R("tests/walkthrough/artifacts/marketing/beta-page.md"), "utf8"); const ok = validateArtifact(art, loam, { lensReads: null }); const m2 = { ...loam, claims: new Map([...loam.claims].map(([k, v]) => [k, k === "C1" ? { ...v, grade: "REPORTED" } : v])) }; const bad = validateArtifact(art, m2, { lensReads: null }); return [ok.length === 0 && bad.length === 1 && /REPORTED/.test(bad[0]), `accepted [] then refused: ${bad[0]}`]; },
  C4: () => { const s = parseStamp(fs.readFileSync(R("tests/walkthrough/artifacts/marketing/beta-page.md"), "utf8")); return [staleReasons(s, loam).length === 0 && staleReasons({ ...s, built: 3 }, loam).includes("D10"), "current at model@4; stale by D10 when built from model@3"]; },
  C5: () => { const w = waves(lensMap, ["recon-software", "brand", "direction", "experience", "marketing", "illustration", "motion-editorial", "audio-sound", "fidelity-qa", "provenance-licensing", "release-readiness"]); return [w.length === 4, `${w.length} waves`]; },
  C6: () => { const t = sh("bun test tests/hooks 2>&1 | tail -4"); return [/ 0 fail/.test(t.out) && /computeGate/.test(read("hooks/src/process.mjs")), t.out.split("\n").filter((l) => /pass|fail/.test(l)).join(", ")]; },
  C8: () => { const o = "/tmp/rr-binary"; sh(`rm -rf ${o}; mkdir -p ${o}/w`); const b = sh(`bun cockpit/build.ts --out ${o}/dist 2>&1 | tail -1`); const run = sh(`cd ${o}/w && env -i PATH=/usr/bin:/bin HOME=${o}/w ${o}/dist/bin/actualize lenses | grep -c '^[a-z]'; env -i PATH=/usr/bin:/bin HOME=${o}/w ${o}/dist/bin/actualize begin --goal "binary smoke for release readiness" --bar demo | head -1`); return [/^17/.test(run.out.trim()) && /run opened/.test(run.out), `${b.out.trim().slice(0, 60)} | lenses ${run.out.split("\n")[0]}; ${run.out.split("\n")[1]}`]; },
  C12: () => [/AUTHORITY_HUMAN/.test(read("cockpit/server/control.ts")) && /AUTHORITY_HUMAN/.test(read("tests/cockpit/workbench.transport.test.ts")), "refusal in control.ts and asserted in the transport test"],
  C13: () => { const h = JSON.parse(read("actualize/evidence/dogfood/R1-history.json")); return [REQUEST_STATUSES.includes("queued") && h.request.history[0].status === "queued", `R1 history begins ${h.request.history[0].status}`]; },
  C14: () => [fs.existsSync(R("actualize/evidence/dogfood/02-request-queued.png")), "screenshot present; its text read during the run"],
  C15: () => { const t = sh("python3 tests/check.py 2>&1 | tail -1"); return [t.out.trim() === "OK", "tests/check.py: " + t.out.trim()]; },
  C16: () => [/must be able to fail/.test(read("tests/check.py")), "mutation harness in tests/check.py"],
  C17: () => { const l = sh("head -1 LICENSE").out; const g = sh("git log origin/main..HEAD --oneline | grep -c 5118770").out.trim(); const remote = sh("git show origin/main:LICENSE | head -1").out.trim(); return [/AFFERO/.test(l) && g === "1", `local ${l.trim()}; unpushed commit 5118770: ${g === "1" ? "yes" : "no"}; origin/main still: ${remote}`]; },
  C18: () => [JSON.parse(read("package.json")).private === true && sh("gh release list --repo SPRIME01/Product-Actualizer --limit 2").out.trim() === "", "private:true; no releases listed"],
  C19: () => [/race/.test(read("actualize/evidence/recon-software/clean-checkout.txt")) && /opened\(/.test(read("tests/cockpit/workbench.e2e.test.ts")), "fix present (opened helper); suite result recorded in the clean-room step"],
  C20: () => { const c = JSON.parse(read("actualize/evidence/dogfood/capabilities-before.json")).capabilities; const find = (n, i) => c.find((x) => x.id === n)?.candidates.find((y) => y.name === i)?.found; return [find("motion-editorial", "ffmpeg") === "found" && find("motion-editorial", "hyperframes") === "unknown", `ffmpeg ${find("motion-editorial", "ffmpeg")}, hyperframes ${find("motion-editorial", "hyperframes")}`]; },
  C21: () => [/Linux x86_64/.test(read("actualize/evidence/recon-software/executed-checks-binary.txt")), "binary evidence names Linux x86_64 only"],
  C22: () => { const bad = Object.values(lensMap).filter((l) => !l.description || !l.reads.length); return [bad.length === 0, `${Object.keys(lensMap).length} lenses with description and reads`]; },
  C23: () => { const t = read("hooks/install.mjs"); return [["claude", "codex", "cline", "opencode", "prime"].every((n) => t.includes(`import * as ${n}`)), "five adapters imported"]; },
  C26: () => web("https://stackoverflow.co/company/press/archive/stack-overflow-2025-developer-survey/", ["84%", "46%", "31%"]),
  C27: () => web("https://arxiv.org/abs/2609.20812", ["67.9%", "80.4%"]),
  C28: () => web("https://martinfowler.com/articles/exploring-gen-ai/sdd-3-tools.html", ["spec-first", "spec-anchored", "spec-as-source", "LOT of markdown"]),
  C29: async () => { const g = (r) => +sh(`gh api repos/${r} --jq .stargazers_count`).out.trim(); const v = [g("github/spec-kit"), g("Fission-AI/OpenSpec"), g("bmad-code-org/BMAD-METHOD")]; return [v[0] >= 139998 && v[1] >= 70977 && v[2] >= 53753, `today ${v.join(", ")}; claim is dated 2026-10-03 (139998, 70977, 53753)`]; },
  C30: () => web("https://appelixir.com/articles/ai-app-builder-comparison-lovable-bolt-v0-replit/", ["None of them owns the whole lifecycle"]),
  C31: () => web("https://dev.to/kentkandiforge/the-last-mile-problem-in-agentic-development-5768", ["bottleneck isn't building anymore"]),
  C32: async () => { const a = await web("https://developers.openai.com/codex/skills", ["open agent skills standard", "SKILL.md"]); const b = await web("https://cursor.com/docs/skills", ["SKILL.md"]); return [a[0] && b[0], `codex: ${a[1]}; cursor: ${b[1]}`]; },
  C33: async () => { const a = await web("https://hunchbite.com/hire-developer-ai-app", ["handoff"]); const b = await web("https://kitrum.com/services/ai-code-handoff-services/", ["handoff"]); return [a[0] && b[0], `hunchbite: ${a[1]}; kitrum: ${b[1]}`]; },
  C34: async () => { const r = await Promise.all(["https://www.warrant.build/", "https://warrantai.dev/", "https://www.plumblinehq.ai/"].map((u) => web(u, []))); return [r.every((x) => x[0]), r.map((x) => x[1]).join("; ")]; },
  C38: () => [/fake incomplete/.test(read("README.md")) && /fictional desk robot/.test(read("README.md")), "README.md lines 30 and 31"],
  C39: () => [fs.existsSync(R("actualize/product-model.md")) && fs.readdirSync(R("actualize/history")).length >= 8, `${fs.readdirSync(R("actualize/history")).length} model snapshots`],
  C40: () => [["01-show-the-workflow", "02-request-queued", "03-ready-for-review", "04-accepted"].every((n) => fs.existsSync(R(`actualize/evidence/dogfood/${n}.png`))), "four screenshots present"],
  C41: () => { const h = JSON.parse(read("actualize/evidence/dogfood/R1-history.json")).request.history.map((x) => x.status).join(">"); return [h === "queued>acknowledged>running>produced>ready_for_review>accepted", h]; },
  C43: async () => { const it = await (await fetch("https://hacker-news.firebaseio.com/v0/item/48558502.json")).json(); const t = norm(it.text ?? ""); return [t.includes("instructions are not guarantees.") && t.includes("a rule is an enforcement mechanism"), `HN item 48558502 by API, ${new Date(it.time * 1000).toISOString().slice(0, 10)}`]; },
  C44: () => { const sz = (p) => fs.statSync(R(p)).size; const lensF = fs.readdirSync(R("skills")).filter((d) => d !== "actualize-product" && d !== "cockpit").map((d) => R("skills", d, "SKILL.md")); const tot = lensF.reduce((n, f) => n + fs.statSync(f).size, 0); return [sz("skills/actualize-product/SKILL.md") + sz("product-model/SCHEMA.md") === 12195 && tot === 160045, `always loaded ${sz("skills/actualize-product/SKILL.md") + sz("product-model/SCHEMA.md")}, lens files ${tot}`]; },
  C45: () => [/lens bodies load only through/.test(read("hooks/src/engine.mjs")), "engine.mjs denial text present"],
  C56: () => [["brand/fonts/OFL-atkinson-hyperlegible-next.txt", "brand/fonts/OFL-jetbrains-mono.txt"].every((f) => /SIL OPEN FONT LICENSE Version 1.1/i.test(read(f))), "both license texts say OFL 1.1"],
  C57: () => web("https://fish.audio/s2/", ["Research and non-commercial use is permitted free of charge"]),
  C58: () => { let n = 0, h = 0; for (const pat of ["sk-or-v1-[A-Za-z0-9]{20,}", "sk-ant-[A-Za-z0-9_-]{20,}", "ghp_[A-Za-z0-9]{30,}", "github_pat_[A-Za-z0-9_]{30,}", "AKIA[0-9A-Z]{16}", "-----BEGIN [A-Z ]*PRIVATE KEY-----"]) { n += +sh(`grep -rEIl '${pat}' . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=.cockpit --exclude-dir=dist 2>/dev/null | wc -l`).out.trim(); h += +sh(`git log --all -G'${pat}' --oneline | wc -l`).out.trim(); } return [n === 0 && h === 0, `${n} files, ${h} history commits with a full-token match (the pattern text alone, as in secret-scan.txt, is not a match)`]; },
  C11: () => { const t = sh("grep -rEn 'api\\.(openai|anthropic)\\.com|openrouter\\.ai|generativelanguage|api\\.cohere|api\\.mistral|@anthropic-ai/sdk|from \"openai\"' hooks cockpit --include=*.ts --include=*.tsx --include=*.mjs --include=*.js | wc -l").out.trim(); return [t === "0" && /show the workflow/.test(read("cockpit/server/terminal.ts")), `${t} provider references in hooks/ and cockpit/; terminal.ts handles "show the workflow" with local rules`]; },
  C55: async () => { const ids = [47343927, 47197595, 48558502]; const r = []; for (const id of ids) { const it = await (await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`)).json(); r.push(`${id}: ${it?.type} score ${it?.score} comments ${it?.descendants}`); } return [r.every((x) => /: story score \d+/.test(x)), r.join("; ")]; },
  C59: () => [qaOk("C3"), "site-qa check C3 (byte identity)"], C60: () => [qaOk("D9"), "site-qa check D9"], C61: () => [qaOk("D1", "D3"), "site-qa checks D1, D3"], C62: () => [qaOk("D7"), "site-qa check D7"],
  C63: () => [qaOk("L1", "T3", "K1", "M1"), "site-qa checks L1, T3, K1, M1"], C67: () => [qaOk("P1"), "site-qa check P1"],
  C64: () => { const a = read("actualize/evidence/motion-editorial/determinism-run1.json"), b = read("actualize/evidence/motion-editorial/determinism-run2.json"); return [a === b && /"digest"/.test(a), a.trim().slice(0, 90)]; },
  C65: () => { const t = read("actualize/evidence/motion-editorial/probe.txt"); return [/duration=72\.4/.test(t) && /I:\s+-16\.2 LUFS/.test(t) && /0\.39 frames/.test(t) && /\n0\n/.test(t), "72.4 s, -16.2 LUFS, 0.39 frame, 0 digital-silence runs"]; },
  C66: () => { const L = read("actualize/evidence/audio-sound/tts-calls.jsonl").trim().split("\n").map((l) => JSON.parse(l)); return [L.length >= 10 && L.every((x) => x.model === "fish-audio/s2.1-pro-free:free" && x.status === 200 && x.contentType === "audio/mpeg" && x.generationId), `${L.length} logged calls, all 200 audio/mpeg with generation ids`]; },
  C69: async () => { const it = await (await fetch("https://hacker-news.firebaseio.com/v0/item/49525494.json")).json(); const t = norm(it.text ?? ""); return [t.includes("are these videos of it eg tidying up real or just staged"), `HN item 49525494 by ${it.by}, ${new Date(it.time * 1000).toISOString().slice(0, 10)}`]; },
  C70: async () => { const it = await (await fetch("https://hacker-news.firebaseio.com/v0/item/49529412.json")).json(); const t = norm(it.text ?? ""); return [t.includes("none of the videos on website say how much are they speed up") && t.includes("teleoperated"), `HN item 49529412 by ${it.by}`]; },
  C71: () => { const names = Object.keys(lensMap); const need = ["recon-physical", "electronics", "embedded-systems", "robotics", "product-visualization", "brand", "direction", "experience", "illustration", "marketing", "motion-editorial", "audio-sound", "fidelity-qa", "provenance-licensing", "legacy-modernization", "recon-software", "release-readiness"]; return [need.every((n) => names.includes(n)) && names.length === 17, `${names.length} lenses, all named lenses present`]; },
  C72: () => { const g = read("tests/walkthrough-mote/artifacts/release-readiness/gate.md"); return [parseStamp(g).head.verdict === "no-go" && /PHY\d+/.test(g), "verdict no-go; physical evidence walk present"]; },
  C73: () => [/Physical claims need physical evidence/.test(read("skills/release-readiness/SKILL.md")) && /real unit/.test(read("skills/release-readiness/SKILL.md")), "heading and rule present in the lens"],
  C79: () => { const t = read("actualize/evidence/motion-editorial-3/probe.txt"); return [/video 80\.6\d+s/.test(t) && /I:\s+-16\.0 LUFS/.test(t) && /difference 0\.4\d frames/.test(t) && /\n0\n/.test(t) && /width=1920 height=1080/.test(t) && /color_space=bt709/.test(t), "80.6 s, 1920x1080, BT.709, -16.0 LUFS, 0.46 frame, 0 digital-silence runs"]; },
  C80: () => { const a = read("actualize/evidence/motion-editorial-3/determinism-run1.json"), b = read("actualize/evidence/motion-editorial-3/determinism-run2.json"); return [a === b && /"digest"/.test(a), a.trim().slice(0, 90)]; },
  C81: () => { const sc = read("media/explainer-3/tools/score.mjs"); const cues = read("media/explainer-3/src/cues.mjs"); const film = read("media/explainer-3/src/film.mjs"); const noAudioFiles = !fs.readdirSync(R("media/explainer-3"), { recursive: true }).some((f) => /\.(mp3|wav|ogg|flac)$/.test(f) && !/^(audio|renders)\//.test(f)); return [/Synthesises the film's score/.test(sc) && /import \{ events \} from "..\/src\/cues.mjs"/.test(sc) && /import \{ events \} from "\.\/cues.mjs"/.test(film) && /export function events/.test(cues) && !/fetch\(/.test(sc) && noAudioFiles, "score.mjs synthesises from code, reads cues.mjs (as film.mjs does), has no network call, and no audio file is vendored outside audio/ and renders/"]; },
  C82: () => { const L = read("actualize/evidence/audio-sound/tts-calls-3.jsonl").trim().split("\n").map((l) => JSON.parse(l)); return [L.length >= 8 && L.every((x) => x.model === "fish-audio/s2.1-pro-free:free" && x.status === 200 && /^audio\//.test(x.contentType) && x.voice === "b347db033a6549378b48d00acb0d06cd" && x.generationId), `${L.length} calls, all 200 audio, pinned voice, generation ids logged`]; },
  C68: () => [sh("git log -1 --format=%h 931a76f").out.trim() === "931a76f" && fs.existsSync(R("actualize/history/model-v6.md")), "commit 931a76f and history snapshots present"],
};
const rows = []; let fails = 0;
for (const [id, files] of [...cited].sort((a, b) => +a[0].slice(1) - +b[0].slice(1))) {
  const c = model.claims.get(id); let res;
  if (!c || !PUBLIC_GRADES.has(c.grade)) res = [false, `grade ${c?.grade ?? "missing"}`];
  else if (!checks[id]) res = [false, "no re-check defined"];
  else { try { res = await checks[id](); } catch (e) { res = [false, "error: " + e.message.slice(0, 80)]; } }
  if (!res[0]) fails++; rows.push({ id, grade: c?.grade, files: files.join(", "), pass: res[0], detail: res[1] });
  console.log((res[0] ? "PASS " : "FAIL ") + id + " " + String(res[1]).slice(0, 110));
}
const dir = import.meta.dir;
fs.writeFileSync(path.join(dir, "ledger-walk.json"), JSON.stringify({ at: new Date().toISOString(), model: model.version, rows }, null, 1));
fs.writeFileSync(path.join(dir, "ledger-walk.md"), `# Ledger walk at model@${model.version}, ${new Date().toISOString().slice(0, 10)}\n\nEvery claim cited by a public artifact, with the re-check run now.\n\n| id | grade | cited by | result | what was re-run |\n|---|---|---|---|---|\n` + rows.map((r) => `| ${r.id} | ${r.grade} | ${r.files.replace(/\|/g, "/")} | ${r.pass ? "pass" : "FAIL"} | ${String(r.detail).replace(/\|/g, "/")} |`).join("\n") + `\n\n${rows.length - fails} of ${rows.length} passed.\n`);
console.log(`\n${rows.length - fails}/${rows.length}`); process.exit(fails ? 1 : 0);
